app:
    notFound:
        code: 404
        content-type: 'application/json'
        body: '{
                "data" : "route not found"
            }'
    routes:
        /test3:
            code: 200
            content-type: 'application/json'
            body: '{
                "token" : "data for test1"
            }'
        /test4:
            code: 200
            content-type: 'application/json'
            body: '{
                "data" : "data for test2"
            }'